settings:
  combat-tag-duration: 30             # Duration (in seconds) a player is tagged in combat
  reengagement-duration: 30           # Additional seconds added when combat is re-engaged
  doppel-swap-duration: 30            # Additional seconds added when a Doppel swaps in
  max-duration: 30                    # Maximum duration of combat (in seconds)
  max-session-length: 300             # Maximum total session length (in seconds)
  debug-mode: true                   # Enables debug logging for more detailed output
  custom-death-messages: true         # Whether custom death messages are enabled

messages:
  in-combat: "&cYou are in combat for %seconds% more seconds!"
  no-longer: "&aYou are no longer in combat."
  combat-engaged: "&cYou have entered combat!"
  combat-engaged-projectile: "&cYou have entered combat due to projectile!"
  combat-death: "&c%victim% was slain by %killer% in combat!"
  combat-kill: "&aYou are no longer in combat after defeating %victim%!"
  combat-log-death: "&cYou were killed by &6%killer%&c while logged out."
  still-in-combat: "&cYou are still in combat!"
  offline-death: "&cYou were killed by &6%killer%&c while logged out."
