name: KillionCombatLog
version: '1.0-SNAPSHOT'
main: co.killionrevival.killionCombatLog.KillionCombatLog
authors: [tut, flyerz, Fross]
api-version: '1.18'
depend: [WorldGuard, KillionCommons, Citizens]
commands:
  killioncombatlog:
    usage: /<command> <reload>
    description: A command to control the KillionCombatLog system.
    aliases:
      - kcl
    permission: killioncombatlog.reload